apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-api
  template:
    metadata:
      labels:
        app: ecommerce-api
    spec:
      containers:
        - name: ecommerce-api
          image: ecommerce-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/ecommerce_db
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret
                  key: DB_PASSWORD
            - name: CRYPT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret
                  key: CRYPT_SECRET_KEY
            - name: ADMIN_FIRST_EMAIL
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret
                  key: ADMIN_FIRST_EMAIL
            - name: CORREIOS_API_URL
              value: https://api.correios.com.br
            - name: MERCADO_PAGO_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret
                  key: MERCADO_PAGO_PUBLIC_KEY
            - name: MERCADO_PAGO_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret
                  key: MERCADO_PAGO_ACCESS_TOKEN
          volumeMounts:
            - name: uploads-storage
              mountPath: /app/uploads
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ecommerce-api
