apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
type: Opaque
data:
  DB_PASSWORD: bXUlQ2o2Wkx5UFVOTVh4czBQIWI=
  CRYPT_SECRET_KEY: M2RwcmludHBuZ3N1cGVyc2VjcmV0a2V5MjAyNjEyMzQ=
  ADMIN_FIRST_EMAIL: cGF0cmlja21vdXJhQGdtYWlsLmNvbQ==
  MERCADO_PAGO_PUBLIC_KEY: VEVTVC1YWFhYWFhYWC1YWFhYLVhYWFgtWFhYWC1YWFhYWFhYWFhYWFg=
  MERCADO_PAGO_ACCESS_TOKEN: VEVTVC1YWFhYWFhYWFhYWFhYWFhYLVhYWFhYWC1YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFg=
